### ISSUE TITLE
`ws setup` doesn't work, returns "No help topic for 'setup'"

### ISSUE THREAD

**Issue by tylerfowle** [windler/ws#2]
![screen shot 2018-07-23 at 10 19 10 am](https://user-images.githubusercontent.com/7574003/43086007-f6d00e14-8e61-11e8-9a59-861b7e1ba5fc.png)

**Comment by windler** [comment]
Thank you for opening this issue.

Unfortunately, this is a hint to a command that was planned but never implemented (the setup command was planned to create the config file by user inputs). For now, I will just remove this hint.

Did you manage to fix your actual problem `open ~/Projects: no such file or directory`? Does this output provide enough information for you?

**Comment by tylerfowle** [comment]
@windler i was able to get it setup.  but none of the commands work.  when I run `ws code [my_project]` nothing happens

here is my `~/.wshero`
```
wsdir: /Users/tyler.fowle/Repos/
tableformat: "{{cmd \"pws\" .}}|{{gitStatus .}}|{{gitBranch .}}"
customcommands:
- name: pws
  description: "print the current ws name"
  cmd: echo
  args:
  - "{{.WSRoot}}"
- name: code
  description: "edit ws in nvim"
  cmd: "nvim"
  args:
  - "{{.WSRoot}}"
```
